using System;
using System.Collections.Generic;
using System.Text;

namespace ExtCore.Data.Entities.Abstractions
{
    public  interface ISystemEntity
    {
        /// <summary>
        /// Entity that can be generated by system
        /// </summary>
        bool IsSystemEntity { get; set; }
    }
}
